Measurement errors V0.2
sebgrijalva/Pulser pull request #2
Opened 2021-04-07 12:15 UTC by julienbremont

2021-04-07 12:25 UTC, sebgrijalva commented on pulser/simresults.py
> +            probs = np.abs(final_state.full())**2
There seems to be some conflict here. I would say the line above is right since we use the `.full()` method to extract only the numpy array and not the Qobj.

2021-04-07 22:29 UTC, sebgrijalva reviewed
Nice job! I'm adding some comments on the SPAM errors methods, please see if you agree and try to commit the changes you think will improve the file.

2021-04-07 22:29 UTC, sebgrijalva commented on pulser/simresults.py
> +                    P_joint[b] *= P[k, int(b[k])]
I suggest writing this using list-comprehension: 

```python
bitstrings = [np.binary_repr(i,N) for i in range(2**N)]
P_joint = {bitstring: np.prod([P[k, int(bit)] for k, bit in enumerate(bitstring)]) 
                                   for bitstring in bitstrings}

2021-04-07 22:29 UTC, sebgrijalva commented on pulser/simulation.py
> +            epsilon = 0
No need to initialize `epsilon`, Python handles this everytime you redefine it inside the `for` loop below

2021-04-07 22:29 UTC, sebgrijalva commented on pulser/simulation.py
> +                        slot.type.detuning.samples[i-slot.ti] * (1+epsilon)
Try using a single array for the noise and then adding, it's faster:
```python
noise = 1 + np.random.normal(0, 2*np.pi*0.12, slot.tf - slot.ti +1)
samples_dict['det'][slot.ti:slot.tf] += slot.type.detuning.samples + noise
```

2021-04-08 05:47 UTC, julienbremont commented
Added your changes ! Thanks !

2021-04-16 15:36 UTC, julienbremont commented
Updated my branch with the new methods, everything should work properly.

2021-04-21 16:29 UTC, sebgrijalva reviewed
Here are some changes that could be implemented. Most importantly, I think an "Abstract Base Class" could be useful for this design.

2021-04-21 16:29 UTC, sebgrijalva commented on pulser/simresults.py
> +    """Results of a simulation run of a pulse sequence. Parent class for
Let's try to put `CleanResults`and `NoisyResults` in the same file `simresults.py`; and make `SimulationResults` an [Abstract Base Class](https://www.geeksforgeeks.org/abstract-classes-in-python/) (the link shows a nice template/example that implements this)

2021-04-21 16:29 UTC, sebgrijalva commented on pulser/noisy_results.py
> +            proj = qutip.tensor([self.basis[i] * self.basis[i].dag() for i
Try the `proj()` method:
```
proj = qutip.tensor([self.basis[i].proj() for i in bitstring])
```

2021-04-21 16:29 UTC, sebgrijalva commented on pulser/noisy_results.py
> +        density_matrix = 0
Try Python's `sum()` :

```
density_matrix = sum(v * _proj_from_bitstring(b) for b, v in self._states.items())
```

2021-04-21 19:56 UTC, julienbremont commented on pulser/simresults.py
> +            str(i): qutip.basis(2, i) for i, b in enumerate(basis)}
This was actually useless, thanks for pointing it out ! We don't need a basis because we already have everything in terms of 0's and 1's.

2021-04-21 19:56 UTC, julienbremont commented on pulser/simresults.py
> +            basis = ['g', 'h']
See above issue

2021-04-21 19:58 UTC, julienbremont commented on pulser/noisy_results.py
> +            proj = qutip.tensor([self.basis[i] * self.basis[i].dag() for i
Indeed, thanks ! Also used qutip.basis(2, i) instead, since we don't need a basis field in NoisyResults.

2021-04-21 20:22 UTC, julienbremont commented on pulser/simresults.py
> +    """Results of a simulation run of a pulse sequence. Parent class for
Indeed, this'll make code cleaner. Done !

2021-04-22 13:08 UTC, sebgrijalva requested changes
Nice work! Here are some new comments. This is beginning to converge already!

2021-04-22 13:10 UTC, sebgrijalva commented
Also please make sure you sync with the latest version of my fork. Notice that `v0.2`is no longer a branch (we merged it to `master`in the latest release) so this branch should reflect what is currently in my `develop`branch.

2021-04-23 08:37 UTC, julienbremont commented on pulser/simresults.py
> +        self._dim = 2
Actually, the only way to create a NoisyResults object is through sim.run(spam=True), and the simulation allows for 3-level noisy simulations : it's simply that, at the end of the process, you get a "projected states" distribution in the form of bitstrings... Maybe we don't have to check because there is no way to create a 3-level NoisyResults object.

2021-04-23 08:37 UTC, julienbremont commented on pulser/simresults.py
> +                   b, v in self._states.items())
Yes ! I checked :)

2021-04-23 08:43 UTC, julienbremont commented on pulser/simresults.py
> +            probs = probs.reshape(tuple(3 for _ in range(N)))
Alright ! Thanks for the insight, I changed it.

2021-04-23 08:47 UTC, julienbremont commented on pulser/simresults.py
> +        probs = [self._states[b] for b in bitstrings]
Just tried it, the problem is that we need all bitstrings to sample with the multinomial and self._states has been trimmed to only contain non-empty states... I know this is rather costly.

2021-04-23 09:38 UTC, julienbremont commented on pulser/simresults.py
> +        probs = [self._states[b] for b in bitstrings]
Nevermind, I fixed it by writing `probs = list(self._states.values())`. Thanks !

2021-04-30 08:02 UTC, sebgrijalva approved these changes
LGTM

2021-04-30 08:04 UTC, sebgrijalva requested changes
One last thing, could you please rename the tutorials (with some tag like `noise`) so that they don't overwrite the originals? Thanks!

2021-04-30 08:10 UTC, sebgrijalva approved these changes

2021-04-30 08:11 UTC, merged